{% set version = "2.0.5" %}

package:
  name: bob.db.casme2
  version: {{ version }}

source:
  fn: bob.db.casme2-{{ version }}.zip
  md5: 2219b148e26fef60fba288d1aacc4385
  url: https://pypi.python.org/packages/c5/c0/4086cb8a30c83ac6756b050139cd76953c22f046eef2ad949c4bc564a98a/bob.db.casme2-{{ version }}.zip

build:
  number: 0
  skip: true  # [not linux]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - six
    - bob.db.base
    - bob.db.verification.utils

  run:
    - python
    - six
    - bob.db.base
    - bob.db.verification.utils

test:
  commands:
    - bob_dbmanage.py casme2 download
    - nosetests -sv bob.db.casme2

  imports:
    - bob
    - bob.db
    - bob.db.casme2

  requires:
    - nose

about:
  home: https://github.com/bioidiap/bob.db.casme2
  license: GNU General Public License v3 (GPLv3)
  summary: CASME2  Database Access API for Bob

extra:
  recipe-maintainers:
    - 183amir
