travis:
  secure:
    BINSTAR_TOKEN: R/4kFYeWojzl1RONJpv5MqGuXTg1OVZwovkiV6ksK2Jw9UuWCD/MUEU5kimYJtyTmmeDqFpg7VSn6X5dKyw0/hQH1UOrhrorqJO1xwp7ItWmm0ENXF5ulj1ELPB9EOnzC+jjxrhli7i56Axbnayg5I8kAecGLJ69ce1mR2uTUbu/AdQnDQ67QuD7eSlWEOEv8/b9w4jAAP2rdyN0vO0fmRESgPvUur//ZpFdoPv8GKLSZfPrNnVc/VvNr+ebz4jZ4eAEsXJKJf1TTb0oWjbBi/bBPph1Wamcb4hHvJuv09JtlpPcvXirbKN6yLcVMGYtSItotAQ+8H6QqhCHpYZwo5srokrgoAcF7MOYgbHaFKO+mGzCTpvq9irYLV7oWV6FvWibRub1aUwJQSql7isQQRkovOGgKZAiHlGJL0jehGNVrv93datwPhCYjp3dt5ihSCsrq6GQz5iGP4hwQW0nOJFkasS62L2ABBtyUWC3TYHVHa62XUgFtkBhDmlnPUHaOfI+Y/2MD6seydGiZJrekE+BNhFHpVG52T/3TbCeQ5J8pCxg4lvn9ss3GL0hxki7CbhRKY+FJ32YyY2oaxPz2KyebCb37JJ82i7yK6BAc1iwwqzWVjwmVD5HM6umEio2BzJ5JXzpODczATe88uBJ7OABPkDuzuZF3iRcQLlhbrQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
